server:
  port: 8080

# mybatis-plus
mybatis-plus:
  # xml路径
  mapper-locations: classpath:com/theboyaply/orangeJuice/**/mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.theboyaply.orangeJuice.**.domain
  configuration:
    # 自动驼峰转下划线
    map-underscore-to-camel-case: true
    # 关闭缓存
    cache-enabled: false
  global-config:
    # 全局主键策略：分布式ID
    id-type: 2
  # 自定义枚举包
  type-enums-package: com.theboyaply.orangeJuice.**.enums
# mysql
spring:
  servlet:
    multipart:
      # 上传文件的最大值
      max-file-size: 1MB
      # 请求携带参数的最大值
      max-request-size: 2MB
  main:
      allow-bean-definition-overriding: true
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/orangeJuice?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    jdbc-url: jdbc:mysql://127.0.0.1:3306/orangeJuice?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: orange_juice
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 使用hikari连接池。https://www.funtl.com/zh/spring-security-oauth2/基于-JDBC-存储令牌.html
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

# oauth2 clientId配置
security:
  oauth2:
    client:
      clientId: tba
      clientSecret: tbaSecret

# 输出sql log
logging:
  level:
    com.theboyaply.orangeJuice.test.mapper: debug
    com.theboyaply.orangeJuice.web.mapper: debug

# 自定义配置
oj:
  file-path: D:/myResource/securityFile/images/
  file-url-path: http://localhost:80/images/